apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zr3rzq5g8-dotnet-basic
  janus-idp.io/tekton: zr3rzq5g8-dotnet-basic
  backstage.io/kubernetes-id: zr3rzq5g8-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zr3rzq5g8-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
